// Do not edit. This file is machine generated by the Resource DLL Wizard.

library OraTau_plugin;

{ITE} {DFMFileType} {vcl\DBLOGDLG.dfm}
{ITE} {DFMFileType} {vcl\DBPWDLG.dfm}
{ITE} {DFMFileType} {udmData.dfm}
{ITE} {DFMFileType} {uframeScript.dfm}
{ITE} {DFMFileType} {ufrmAbout.dfm}
{ITE} {DFMFileType} {ufrmLogonDialog.dfm}
{ITE} {DFMFileType} {ufrmMain.dfm}
{ITE} {DFMFileType} {ufrmQuickQuery.dfm}
{ITE} {DFMFileType} {ufrmSaveNewFile.dfm}
{ITE} {DFMFileType} {ufrmSchemaAE.dfm}
{ITE} {DFMFileType} {ufrmSchemaGroups.dfm}
{ITE} {DFMFileType} {ufrmSchemaImport.dfm}
{ITE} {DFMFileType} {ufrmSchemaTypes.dfm}
{ITE} {DFMFileType} {ufrmSettings.dfm}
{ITE} {DFMFileType} {ufrmWindows.dfm}
{ITE} {RCFileType} {OraTau_plugin_DRC.rc}

{$R 'vcl\DBLOGDLG.dfm' LoginDialog:TForm(Form)}
{$R 'vcl\DBPWDLG.dfm' PasswordDialog:TForm(Form)}
{$R 'udmData.dfm' dmData:TDataModule}
{$R 'uframeScript.dfm' frameScript:TFrame}
{$R 'ufrmAbout.dfm' frmAbout:TForm}
{$R 'ufrmLogonDialog.dfm' frmLogonDialog:TForm}
{$R 'ufrmMain.dfm' frmMain:TForm}
{$R 'ufrmQuickQuery.dfm' frmQuickQuery:TForm}
{$R 'ufrmSaveNewFile.dfm' frmSaveNewFile:TForm}
{$R 'ufrmSchemaAE.dfm' frmSchemaAE:TForm}
{$R 'ufrmSchemaGroups.dfm' frmSchemaGroups:TForm}
{$R 'ufrmSchemaImport.dfm' frmSchemaImport:TForm}
{$R 'ufrmSchemaTypes.dfm' frmSchemaTypes:TForm}
{$R 'ufrmSettings.dfm' frmSettings:TForm}
{$R 'ufrmWindows.dfm' frmWindows:TForm}
{$R 'OraTau_plugin_DRC.res' 'OraTau_plugin_DRC.rc'}

{$R *.RES}
{$E ENG}

begin
end.